#!/usr/bin/env python3
"""
Coffee grind size analysis — classical computer vision pipeline.

Segments coffee particles from photos taken on an ArUco reference sheet
(generated by generate-reference-sheet.py) and measures their size
distribution.

Pipeline:
    1. Detect ArUco markers (IDs 0-3) in photo
    2. Compute homography → warp to canonical view (known mm/px scale)
    3. White-balance normalise using marker black + paper white references
    4. Segment particles (adaptive threshold + watershed)
    5. Measure each particle (area, equivalent diameter, axes, shape)
    6. Generate visual overlays, distribution plots, pipeline summary
    7. Aggregate across grind settings → correlation plots

Usage:
    # Single image
    python analyze.py photo.jpg --grind-setting 45 --output results/

    # Batch — filename must contain grind setting as a number
    python analyze.py photos/ --output results/

    # Cellpose comparison (requires cellpose + GPU)
    python analyze.py photos/ --model both
"""

from __future__ import annotations

import argparse
import re
import sys
import time
from pathlib import Path

import cv2
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from constants import IMAGE_EXTENSIONS, _relabel_sequential, estimate_grind_setting
from detection import detect_aruco_markers
from measurement import compute_distribution_stats, measure_particles
from preprocessing import (
    get_analysis_mask,
    mask_markers,
    normalize_white_balance,
    warp_to_canonical,
)
from segmentation import segment_cellpose, segment_watershed
from visualization import (
    create_overlay,
    plot_correlation,
    plot_distribution,
    save_comparison,
    save_pipeline_summary,
)


# ---------------------------------------------------------------------------
# Pipeline helpers
# ---------------------------------------------------------------------------

def parse_grind_setting(filepath: str | Path) -> int | None:
    """Extract grind setting (0-100) from filename.  First integer found is used."""
    stem = Path(filepath).stem
    for m in re.finditer(r"(\d+)", stem):
        val = int(m.group(1))
        if 0 <= val <= 100:
            return val
    return None


def preprocess_image(
    image_path: Path,
    grind_setting: int | None,
    output_dir: Path,
) -> dict | None:
    """Load, detect markers, warp, normalise, mask.

    Returns a dict with all preprocessed data, or None on failure.
    """
    print(f"\n{'='*60}")
    print(f"Preprocessing: {image_path.name}  (grind setting: {grind_setting})")
    print(f"{'='*60}")

    image_bgr = cv2.imread(str(image_path))
    if image_bgr is None:
        print(f"  ✗ Could not load image")
        return None

    try:
        marker_centers = detect_aruco_markers(image_bgr)
        print(f"  ✓ Detected all 4 markers")
    except ValueError as e:
        print(f"  ✗ {e}")
        return None

    warped_bgr, mm_per_px = warp_to_canonical(image_bgr, marker_centers)
    print(f"  ✓ Warped ({warped_bgr.shape[1]}×{warped_bgr.shape[0]} px, "
          f"{mm_per_px:.4f} mm/px)")

    normed_bgr = normalize_white_balance(warped_bgr)
    normed_rgb = cv2.cvtColor(normed_bgr, cv2.COLOR_BGR2RGB)
    print(f"  ✓ White-balance normalised")

    masked_bgr = mask_markers(normed_bgr)
    masked_rgb = cv2.cvtColor(masked_bgr, cv2.COLOR_BGR2RGB)
    analysis_mask = get_analysis_mask(normed_bgr.shape[:2])

    img_out_dir = output_dir / image_path.stem
    img_out_dir.mkdir(parents=True, exist_ok=True)
    cv2.imwrite(str(img_out_dir / "warped.jpg"), warped_bgr, [cv2.IMWRITE_JPEG_QUALITY, 95])
    cv2.imwrite(str(img_out_dir / "normalized.jpg"), normed_bgr, [cv2.IMWRITE_JPEG_QUALITY, 95])

    return {
        "image_path": image_path,
        "grind_setting": grind_setting,
        "mm_per_px": mm_per_px,
        "normed_rgb": normed_rgb,
        "masked_rgb": masked_rgb,
        "analysis_mask": analysis_mask,
        "img_out_dir": img_out_dir,
    }


def segment_and_measure(
    prep: dict,
    model_name: str,
    expected_diam_mm: float = 0.7,
) -> dict | None:
    """Run one segmentation model + measure particles.

    Returns a dict with labels, dataframe, overlay, summary — or None on failure.
    """
    masked_rgb = prep["masked_rgb"]
    mm_per_px = prep["mm_per_px"]
    analysis_mask = prep["analysis_mask"]
    grind_setting = prep["grind_setting"]
    image_path = prep["image_path"]

    intermediates = {}
    try:
        if model_name == "cellpose":
            labels = segment_cellpose(masked_rgb, mm_per_px, expected_diam_mm)
        elif model_name == "watershed":
            labels, intermediates = segment_watershed(
                masked_rgb, mm_per_px, return_intermediates=True,
            )
        else:
            print(f"  ✗ Unknown model: {model_name}")
            return None
    except Exception as e:
        print(f"  ✗ {model_name} failed: {e}")
        return None

    n_raw = labels.max()
    image_gray = cv2.cvtColor(masked_rgb, cv2.COLOR_RGB2GRAY)
    df = measure_particles(labels, mm_per_px, analysis_mask, image_gray=image_gray)

    print(f"  ✓ {model_name}: {n_raw} raw → {len(df)} particles", end="")
    if not df.empty:
        med = df["equiv_diameter_mm"].median()
        mean = df["equiv_diameter_mm"].mean()
        print(f"  (median={med:.3f}  mean={mean:.3f} mm)")
    else:
        print()

    # Build overlay using only the labels that survived filtering
    if not df.empty:
        kept = set(df["label"].values)
        filtered = labels.copy()
        filtered[~np.isin(labels, list(kept))] = 0
        filtered = _relabel_sequential(filtered)
    else:
        filtered = np.zeros_like(labels)
    overlay = create_overlay(prep["normed_rgb"], filtered)

    dist_stats = compute_distribution_stats(df)

    summary = {
        "image": image_path.name,
        "grind_setting": grind_setting,
        "model": model_name,
        "n_particles": len(df),
        "median_diameter_mm": round(df["equiv_diameter_mm"].median(), 4) if not df.empty else None,
        "mean_diameter_mm": round(df["equiv_diameter_mm"].mean(), 4) if not df.empty else None,
        "std_diameter_mm": round(df["equiv_diameter_mm"].std(), 4) if not df.empty else None,
        "q25_diameter_mm": round(df["equiv_diameter_mm"].quantile(0.25), 4) if not df.empty else None,
        "q75_diameter_mm": round(df["equiv_diameter_mm"].quantile(0.75), 4) if not df.empty else None,
        "total_area_mm2": round(df["area_mm2"].sum(), 4) if not df.empty else None,
        **dist_stats,
    }

    return {
        "model_name": model_name,
        "labels": labels,
        "df": df,
        "overlay": overlay,
        "summary": summary,
        "intermediates": intermediates,
    }


def save_model_results(prep: dict, result: dict) -> None:
    """Write overlay, distribution plot, CSV, and summary PNG to disk."""
    img_out_dir = prep["img_out_dir"]
    grind_setting = prep["grind_setting"]
    model_name = result["model_name"]
    df = result["df"]
    overlay = result["overlay"]
    image_path = prep["image_path"]

    overlay_bgr = cv2.cvtColor(overlay, cv2.COLOR_RGB2BGR)
    cv2.imwrite(
        str(img_out_dir / f"overlay_{model_name}.jpg"),
        overlay_bgr, [cv2.IMWRITE_JPEG_QUALITY, 95],
    )

    fig = plot_distribution(df, model_name, grind_setting)
    if fig is not None:
        fig.tight_layout()
        fig.savefig(img_out_dir / f"distribution_{model_name}.png", dpi=150)
        plt.close(fig)

    if not df.empty:
        df_out = df.copy()
        df_out["grind_setting"] = grind_setting
        df_out["model"] = model_name
        df_out["image"] = image_path.name
        df_out.to_csv(img_out_dir / f"particles_{model_name}.csv", index=False)

    # Pipeline summary PNG (watershed only — has intermediates)
    if model_name == "watershed":
        save_pipeline_summary(prep, result)


# ---------------------------------------------------------------------------
# Report mode (unlabelled photos)
# ---------------------------------------------------------------------------

def report_process(
    input_paths: Path | list[Path],
    output_dir: Path,
    expected_diam_mm: float = 0.7,
) -> None:
    """Process unlabelled photos and estimate grind settings.

    For each image: preprocess -> segment (watershed) -> measure ->
    estimate DF54 grind setting from median diameter -> save summary.png.
    """
    output_dir.mkdir(parents=True, exist_ok=True)

    if isinstance(input_paths, Path):
        input_paths = [input_paths]

    image_files = _resolve_input_paths(input_paths)
    if not image_files:
        print(f"No images found in {input_paths}")
        sys.exit(1)

    print(f"Report mode: {len(image_files)} image(s)")
    print(f"Output: {output_dir.resolve()}")

    t0 = time.perf_counter()
    reports: list[dict] = []

    for img_path in image_files:
        prep = preprocess_image(img_path, None, output_dir)
        if prep is None:
            continue

        result = segment_and_measure(prep, "watershed", expected_diam_mm)
        if result is None:
            continue

        # Estimate grind setting from median particle diameter
        median_d = result["summary"]["median_diameter_mm"]
        if median_d is not None:
            est = estimate_grind_setting(median_d)
            est_rounded = round(est)
        else:
            est = None
            est_rounded = None

        # Store estimated setting in prep so visualization shows it
        prep["grind_setting"] = est_rounded
        prep["grind_setting_estimated"] = True
        result["summary"]["grind_setting"] = est_rounded
        result["summary"]["estimated_grind_setting"] = round(est, 1) if est is not None else None

        save_model_results(prep, result)

        reports.append({
            "image": img_path.name,
            "median_diameter_mm": median_d,
            "estimated_df54_setting": round(est, 1) if est is not None else None,
            "n_particles": result["summary"]["n_particles"],
            "mean_diameter_mm": result["summary"]["mean_diameter_mm"],
            "std_diameter_mm": result["summary"]["std_diameter_mm"],
            "D10": result["summary"]["D10"],
            "D50": result["summary"]["D50"],
            "D90": result["summary"]["D90"],
            "span": result["summary"]["span"],
            "fines_pct": result["summary"]["fines_pct"],
            "boulders_pct": result["summary"]["boulders_pct"],
            "D_4_3": result["summary"]["D_4_3"],
            "D_3_2": result["summary"]["D_3_2"],
        })

        print(f"  >> Estimated DF54 setting: ~{est_rounded}"
              f"  (median {median_d:.3f} mm)" if median_d else "")

    if not reports:
        print("\nNo images were processed successfully.")
        return

    # Summary table
    report_df = pd.DataFrame(reports)
    report_path = output_dir / "report.csv"
    report_df.to_csv(report_path, index=False)

    print(f"\n{'='*60}")
    print("REPORT")
    print(f"{'='*60}")
    print(report_df.to_string(index=False))
    print(f"\nReport saved to: {report_path}")

    elapsed = time.perf_counter() - t0
    print(f"Total time: {elapsed:.1f}s")


# ---------------------------------------------------------------------------
# Batch processing
# ---------------------------------------------------------------------------

def batch_process(
    input_paths: Path | list[Path],
    output_dir: Path,
    models: list[str],
    grind_setting_override: int | None = None,
    expected_diam_mm: float = 0.7,
) -> None:
    """Process one or more images / directories sequentially.

    For each image: preprocess → segment with each model → save results.
    After all images: write summary CSV and correlation plot.
    """
    output_dir.mkdir(parents=True, exist_ok=True)

    if isinstance(input_paths, Path):
        input_paths = [input_paths]

    image_files = _resolve_input_paths(input_paths)
    if not image_files:
        print(f"No images found in {input_paths}")
        sys.exit(1)

    # Build (path, grind_setting) pairs
    jobs: list[tuple[Path, int]] = []
    for img_path in image_files:
        gs = grind_setting_override if grind_setting_override is not None else parse_grind_setting(img_path)
        if gs is None:
            print(f"⚠  Cannot determine grind setting for {img_path.name} — skipping.")
            continue
        jobs.append((img_path, gs))

    print(f"Found {len(jobs)} image(s)")
    print(f"Models: {', '.join(models)}")
    print(f"Output: {output_dir.resolve()}")

    t0 = time.perf_counter()
    all_summaries: list[dict] = []

    for path, gs in jobs:
        prep = preprocess_image(path, gs, output_dir)
        if prep is None:
            continue

        for model_name in models:
            result = segment_and_measure(prep, model_name, expected_diam_mm)
            if result is not None:
                save_model_results(prep, result)
                all_summaries.append(result["summary"])

        # Comparison image when running multiple models
        if len(models) >= 2:
            save_comparison(prep["img_out_dir"], prep["normed_rgb"], models, gs)

    if not all_summaries:
        print("\nNo images were processed successfully.")
        return

    # Aggregate summary
    summary_df = pd.DataFrame(all_summaries)
    summary_path = output_dir / "summary.csv"
    summary_df.to_csv(summary_path, index=False)
    print(f"\n{'='*60}")
    print(f"Summary saved to: {summary_path}")
    print("\n" + summary_df.to_string(index=False))

    if len(summary_df["grind_setting"].dropna().unique()) > 1:
        plot_correlation(summary_df, output_dir)

    elapsed = time.perf_counter() - t0
    print(f"\nTotal time: {elapsed:.1f}s")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Coffee grind size analysis — classical CV pipeline",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python analyze.py photo.jpg --grind-setting 45
  python analyze.py photos/ --output results/
  python analyze.py photos/ --model both          # watershed + cellpose comparison
  python analyze.py photo.jpg --report             # estimate grind setting
        """,
    )
    parser.add_argument(
        "input",
        type=Path,
        nargs="+",
        help="Image file(s) or directory of images",
    )
    parser.add_argument(
        "-o", "--output",
        type=Path,
        default=Path("results"),
        help="Output directory (default: results/)",
    )
    parser.add_argument(
        "-m", "--model",
        choices=["watershed", "cellpose", "both"],
        default="watershed",
        help="Which model(s) to run (default: watershed)",
    )
    parser.add_argument(
        "-g", "--grind-setting",
        type=int,
        default=None,
        help="Override grind setting for all images (0-100)",
    )
    parser.add_argument(
        "--expected-diam",
        type=float,
        default=0.7,
        help="Expected particle diameter in mm for Cellpose (default: 0.7)",
    )
    parser.add_argument(
        "--report",
        action="store_true",
        help="Report mode: estimate grind setting from unlabelled photos",
    )
    args = parser.parse_args()

    if args.report:
        report_process(args.input, args.output, args.expected_diam)
        return

    if args.model == "both":
        models = ["cellpose", "watershed"]
    else:
        models = [args.model]

    batch_process(args.input, args.output, models, args.grind_setting, args.expected_diam)


def _resolve_input_paths(inputs: list[Path]) -> list[Path]:
    """Expand a mix of files and directories into a flat list of image files."""
    image_files: list[Path] = []
    for p in inputs:
        if p.is_file() and p.suffix.lower() in IMAGE_EXTENSIONS:
            image_files.append(p)
        elif p.is_dir():
            image_files.extend(
                f for f in sorted(p.iterdir())
                if f.suffix.lower() in IMAGE_EXTENSIONS
            )
        else:
            print(f"⚠  Skipping {p} (not a recognised image file or directory)")
    return sorted(set(image_files), key=lambda f: f.name)


if __name__ == "__main__":
    main()
